name: esprit
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_staggered_grid_view: ^0.7.0
  http: ^1.2.2
  cupertino_icons: ^1.0.6
  material_design_icons_flutter: ^7.0.7296
  intl: ^0.19.0
  dialog_flowtter:
  shared_preferences: ^2.0.15


  chart_it: ^0.2.2
  pie_chart: ^5.4.0
  carousel_slider: ^5.0.0
  google_fonts: ^6.2.1
  url_launcher: ^6.0.9
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  location: ^6.0.2
  syncfusion_flutter_charts: ^26.2.11
  fl_chart: ^0.69.0



  weather: ^3.1.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/